In [1]:
A = matrix([[1,-1,2],
           [-1,1,0],
           [-1,0,1]])
F=matrix([[3,1],[1,3]])
C=matrix([[1, 2,-1],
          [1, 0, 1],
          [4,-4, 5]])
D=matrix([[1,1],
    [2,0]])
E=matrix([[-1,1],
    [2,-2]])
G=matrix([[3, -1,0],
          [-1, 2, -1],
          [0,-1, 3]])

In [2]:
pA=A.charpoly() #comando para hallar el polinomio caracteristico
pA

x^3 - 3*x^2 + 4*x - 2

In [3]:
factor(pA) #comando para factorizar polinomios

(x - 1) * (x^2 - 2*x + 2)

In [4]:
solve((x - 1) * (x^2 - 2*x + 2)==0,x)

[x == (-I + 1), x == (I + 1), x == 1]

In [5]:
pretty_print(A.eigenvectors_right())

[(1,
  [
  (0, 1, 1/2)
  ],
  1),
 (1 - 1*I, [(1, -1*I, -1*I)], 1),
 (1 + 1*I, [(1, 1*I, 1*I)], 1)]

In [6]:
B = matrix([[1,2,1],
           [6,-1,0],
           [-1,-2,-1]])
B

[ 1  2  1]
[ 6 -1  0]
[-1 -2 -1]

In [7]:
pB=B.charpoly() #comando para hallar el polinomio caracteristico
pB

x^3 + x^2 - 12*x

In [8]:
factor(pB) #comando para factorizar polinomios

(x - 3) * x * (x + 4)

In [9]:
solve((x - 3) * x * (x + 4)==0,x)

[x == -4, x == 0, x == 3]

In [10]:
pretty_print(B.eigenvectors_right())

[(3,
  [
  (1, 3/2, -1)
  ],
  1),
 (0,
  [
  (1, 6, -13)
  ],
  1),
 (-4,
  [
  (1, -2, -1)
  ],
  1)]

In [11]:
A1=matrix([[1,1],[0,1],[1,0]])
A=(A1.T)*A1
A

[2 1]
[1 2]

In [12]:
A.charpoly() #polinomio caracteristica

x^2 - 4*x + 3

In [13]:
solve(x^2 - 4*x + 3 ==0,x)

[x == 3, x == 1]

In [14]:
M=matrix([[1,1],[0,1],[1,0]])
M

[1 1]
[0 1]
[1 0]

In [15]:
p=var('p')
pretty_print(solve(p^2+2*p+3,p))

[p == -I*sqrt(2) - 1, p == I*sqrt(2) - 1]

In [16]:
q=matrix([[2,-1,1],
         [1,5,-2],
          [0,1,2]])

In [17]:
Pq=q.charpoly()
pretty_print(Pq)

x^3 - 9*x^2 + 27*x - 27

In [18]:
factor(Pq)

(x - 3)^3

In [19]:
solve((x - 3) * (x - 2) * (x - 1) * (x + 2)==0,x)

[x == -2, x == 1, x == 2, x == 3]

In [26]:
import numpy as np

def power_iteration(A, num_simulations: int):
    # Elegimos un vector aleatorio
    # Es Ortogonal
    b_k = np.random.rand(A.shape[1])
    #print(b_k)
    #print("\n")
    for _ in range(num_simulations):
        #print(b_k)
        b_k1 = np.dot(A, b_k)
        #print(b_k1)
        # Calcula la norma
        b_k1_norm = np.linalg.norm(b_k1)
        #print(b_k1_norm)
        # re normalize the vector
        b_k = b_k1 / b_k1_norm

    return b_k
power_iteration(np.array(G), 1000)

array([ 0.57735027, -0.57735027,  0.57735027])

In [21]:
pretty_print(G)

[ 3 -1  0]
[-1  2 -1]
[ 0 -1  3]

In [22]:
pretty_print(C)

[ 1  2 -1]
[ 1  0  1]
[ 4 -4  5]

In [23]:
import numpy as np

def normalize(x):
    fac = abs(x).max() # Saca el valor abosluto máximo del Vector Columna 
                        #valor propio dominante, autovalor
    print(' fac ', fac)
    x_n = x /x.max() # se multiplica por la inversa del x.maximo dominante
                       # x.max()
    print(x_n, " xn")
    return fac, x_n

x = np.array([1,1,1])
#x= np.random.rand(3)
a = np.array(G)
print('Eigenvalue:', x)
print('Eigenvector:', a)

margen=0.0000000000000000000001
i=0

#for i in range(20):
lambda_1=abs(x).max()
while(true):
    x = np.dot(a, x)
    print(i, ' iesima= ', x)
    i=i+1
    lambda_backup=lambda_1
    lambda_1, x = normalize(x)
    if(abs(lambda_backup-lambda_1)<margen):
        break
print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)


Eigenvalue: [1 1 1]
Eigenvector: [[ 3 -1  0]
 [-1  2 -1]
 [ 0 -1  3]]
0  iesima=  [2 0 2]
 fac  2
[1. 0. 1.]  xn
1  iesima=  [ 3. -2.  3.]
 fac  3.0
[ 1.         -0.66666667  1.        ]  xn
2  iesima=  [ 3.66666667 -3.33333333  3.66666667]
 fac  3.6666666666666665
[ 1.         -0.90909091  1.        ]  xn
3  iesima=  [ 3.90909091 -3.81818182  3.90909091]
 fac  3.909090909090909
[ 1.         -0.97674419  1.        ]  xn
4  iesima=  [ 3.97674419 -3.95348837  3.97674419]
 fac  3.9767441860465116
[ 1.         -0.99415205  1.        ]  xn
5  iesima=  [ 3.99415205 -3.98830409  3.99415205]
 fac  3.9941520467836256
[ 1.         -0.99853587  1.        ]  xn
6  iesima=  [ 3.99853587 -3.99707174  3.99853587]
 fac  3.998535871156662
[ 1.         -0.99963383  1.        ]  xn
7  iesima=  [ 3.99963383 -3.99926767  3.99963383]
 fac  3.9996338337605275
[ 1.         -0.99990845  1.        ]  xn
8  iesima=  [ 3.99990845 -3.9998169   3.99990845]
 fac  3.9999084500595075
[ 1.         -0.99997711  1.      

In [24]:
print(D)

[1 1]
[2 0]


In [25]:
Pd=D.charpoly()
pretty_print(factor(Pd))

(x - 2) * (x + 1)